import { Cliente, Atividade } from '@/types'

export type ClienteComCidade = Cliente & { cidade: string }

export const MOCK_CLIENTES: ClienteComCidade[] = [
  {
    id: 'mock-1', bubble_id: 'mock-1',
    razao_social: 'Supermercado Araújo Ltda',
    cnpj: '12.345.678/0001-90',
    uf: 'CE', cidade: 'Fortaleza',
    consumo_estimado: 48000,
    status_atual: 'Em contato',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-15',
    concorrente_atual: 'ENEL CE',
    data_vencimento_contrato: '2026-10-31',
  },
  {
    id: 'mock-2', bubble_id: 'mock-2',
    razao_social: 'Cerâmica Nordeste Ltda',
    cnpj: '23.456.789/0001-01',
    uf: 'CE', cidade: 'Sobral',
    consumo_estimado: 120000,
    status_atual: 'Proposta',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-30',
    concorrente_atual: 'EDP',
    data_vencimento_contrato: '2026-09-15',
  },
  {
    id: 'mock-3', bubble_id: 'mock-3',
    razao_social: 'Clínica São Lucas S/A',
    cnpj: '34.567.890/0001-12',
    uf: 'CE', cidade: 'Juazeiro do Norte',
    consumo_estimado: 22000,
    status_atual: 'Novo',
    responsavel_id: 'agente-mock',
  },
  {
    id: 'mock-4', bubble_id: 'mock-4',
    razao_social: 'Indústria Têxtil Cearense SA',
    cnpj: '45.678.901/0001-23',
    uf: 'CE', cidade: 'Caucaia',
    consumo_estimado: 85000,
    status_atual: 'Em contato',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-28',
  },
  {
    id: 'mock-5', bubble_id: 'mock-5',
    razao_social: 'Distribuidora Paz e Bem Ltda',
    cnpj: '56.789.012/0001-34',
    uf: 'CE', cidade: 'Fortaleza',
    consumo_estimado: 31000,
    status_atual: 'Perdido',
    responsavel_id: 'agente-mock',
    concorrente_atual: 'CPFL',
    data_vencimento_contrato: '2027-03-01',
  },
  {
    id: 'mock-6', bubble_id: 'mock-6',
    razao_social: 'Shopping Iguatemi Belém SA',
    cnpj: '67.890.123/0001-45',
    uf: 'PA', cidade: 'Belém',
    consumo_estimado: 200000,
    status_atual: 'Proposta',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-27',
    concorrente_atual: 'Celpa',
    data_vencimento_contrato: '2026-11-30',
  },
  {
    id: 'mock-7', bubble_id: 'mock-7',
    razao_social: 'Mineradora Pará Exportações Ltda',
    cnpj: '78.901.234/0001-56',
    uf: 'PA', cidade: 'Marabá',
    consumo_estimado: 350000,
    status_atual: 'Em contato',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-10',
  },
  {
    id: 'mock-8', bubble_id: 'mock-8',
    razao_social: 'Hotel Amazon Palace Ltda',
    cnpj: '89.012.345/0001-67',
    uf: 'PA', cidade: 'Santarém',
    consumo_estimado: 65000,
    status_atual: 'Convertido',
    responsavel_id: 'agente-mock',
  },
  {
    id: 'mock-9', bubble_id: 'mock-9',
    razao_social: 'Gráfica Tropical do Norte Ltda',
    cnpj: '90.123.456/0001-78',
    uf: 'PA', cidade: 'Belém',
    consumo_estimado: 18000,
    status_atual: 'Novo',
    responsavel_id: 'agente-mock',
  },
  {
    id: 'mock-10', bubble_id: 'mock-10',
    razao_social: 'Frigorífico Norte Ltda',
    cnpj: '01.234.567/0001-89',
    uf: 'PA', cidade: 'Marabá',
    consumo_estimado: 95000,
    status_atual: 'Em contato',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-06-05',
    concorrente_atual: 'Celpa',
    data_vencimento_contrato: '2026-08-20',
  },
  {
    id: 'mock-11', bubble_id: 'mock-11',
    razao_social: 'Polo Industrial Paraense SA',
    cnpj: '11.222.333/0001-90',
    uf: 'PA', cidade: 'Belém',
    consumo_estimado: 180000,
    status_atual: 'Proposta',
    responsavel_id: 'agente-mock',
    proximo_follow_up: '2026-07-02',
    concorrente_atual: 'EQUATORIAL',
    data_vencimento_contrato: '2026-09-30',
  },
  {
    id: 'mock-12', bubble_id: 'mock-12',
    razao_social: 'Metalúrgica Cearense Industrial Ltda',
    cnpj: '22.333.444/0001-01',
    uf: 'CE', cidade: 'Fortaleza',
    consumo_estimado: 70000,
    status_atual: 'Convertido',
    responsavel_id: 'agente-mock',
  },
]

export const MOCK_ATIVIDADES: Record<string, Atividade[]> = {
  'mock-1': [
    {
      id: 'at-1-3', agente_id: 'agente-mock', cliente_id: 'mock-1',
      tipo: 'Email', status: 'Atendeu',
      comentario: 'Enviada proposta comercial com análise da conta de luz. Aguardando retorno do financeiro.',
      follow_up_data: '2026-06-15',
      created_at: '2026-06-10T09:15:00Z',
    },
    {
      id: 'at-1-2', agente_id: 'agente-mock', cliente_id: 'mock-1',
      tipo: 'Ligacao', status: 'Atendeu',
      comentario: 'Falei com Rômulo (financeiro). Tem interesse, pediu proposta por e-mail.',
      follow_up_data: '2026-06-10',
      created_at: '2026-06-05T14:30:00Z',
    },
    {
      id: 'at-1-1', agente_id: 'agente-mock', cliente_id: 'mock-1',
      tipo: 'Ligacao', status: 'Nao atendeu',
      follow_up_data: '2026-06-05',
      created_at: '2026-05-28T10:00:00Z',
    },
  ],
  'mock-2': [
    {
      id: 'at-2-2', agente_id: 'agente-mock', cliente_id: 'mock-2',
      tipo: 'Proposta', status: 'Agendou',
      comentario: 'Apresentamos proposta para migração ao livre. Diretoria vai analisar e responde na sexta.',
      follow_up_data: '2026-06-30',
      created_at: '2026-06-20T15:00:00Z',
    },
    {
      id: 'at-2-1', agente_id: 'agente-mock', cliente_id: 'mock-2',
      tipo: 'Reuniao', status: 'Atendeu',
      comentario: 'Reunião presencial com o dono, Sr. Antônio. Muito receptivo. Contrato EDP vence em setembro.',
      follow_up_data: '2026-06-20',
      created_at: '2026-06-12T10:00:00Z',
    },
  ],
  'mock-4': [
    {
      id: 'at-4-1', agente_id: 'agente-mock', cliente_id: 'mock-4',
      tipo: 'Ligacao', status: 'Atendeu',
      comentario: 'Gerente de compras pediu comparativo com contrato atual. Consumo médio de 85 MWh/mês.',
      follow_up_data: '2026-06-28',
      created_at: '2026-06-18T11:00:00Z',
    },
  ],
  'mock-5': [
    {
      id: 'at-5-2', agente_id: 'agente-mock', cliente_id: 'mock-5',
      tipo: 'Declinio', status: 'Recusou',
      comentario: 'Sócio recusou. Fechou com CPFL por preço menor (oferta agressiva). Contrato de 1 ano.',
      follow_up_data: '2027-03-01',
      created_at: '2026-05-30T16:00:00Z',
    },
    {
      id: 'at-5-1', agente_id: 'agente-mock', cliente_id: 'mock-5',
      tipo: 'Proposta', status: 'Agendou',
      comentario: 'Proposta enviada. Estão analisando concorrência.',
      follow_up_data: '2026-05-30',
      created_at: '2026-05-20T09:00:00Z',
    },
  ],
  'mock-6': [
    {
      id: 'at-6-2', agente_id: 'agente-mock', cliente_id: 'mock-6',
      tipo: 'Proposta', status: 'Agendou',
      comentario: 'Proposta entregue para o gerente predial. Volume de 200 MWh/mês. Decisão esta semana.',
      follow_up_data: '2026-06-27',
      created_at: '2026-06-22T14:00:00Z',
    },
    {
      id: 'at-6-1', agente_id: 'agente-mock', cliente_id: 'mock-6',
      tipo: 'Ligacao', status: 'Atendeu',
      comentario: 'Primeiro contato com Juliana (gestão energética). Muito aberta à migração.',
      follow_up_data: '2026-06-22',
      created_at: '2026-06-15T10:30:00Z',
    },
  ],
  'mock-7': [
    {
      id: 'at-7-1', agente_id: 'agente-mock', cliente_id: 'mock-7',
      tipo: 'Ligacao', status: 'Nao atendeu',
      follow_up_data: '2026-06-10',
      created_at: '2026-06-03T09:00:00Z',
    },
  ],
  'mock-8': [
    {
      id: 'at-8-3', agente_id: 'agente-mock', cliente_id: 'mock-8',
      tipo: 'Proposta', status: 'Atendeu',
      comentario: 'Contrato assinado! Hotel vai migrar a partir de agosto. 65 MWh/mês.',
      created_at: '2026-06-01T11:00:00Z',
    },
    {
      id: 'at-8-2', agente_id: 'agente-mock', cliente_id: 'mock-8',
      tipo: 'Reuniao', status: 'Atendeu',
      comentario: 'Reunião de fechamento com diretoria. Aprovado por unanimidade.',
      follow_up_data: '2026-06-01',
      created_at: '2026-05-28T09:00:00Z',
    },
    {
      id: 'at-8-1', agente_id: 'agente-mock', cliente_id: 'mock-8',
      tipo: 'Proposta', status: 'Agendou',
      comentario: 'Enviamos proposta técnica e financeira detalhada.',
      follow_up_data: '2026-05-28',
      created_at: '2026-05-15T14:00:00Z',
    },
  ],
  'mock-10': [
    {
      id: 'at-10-2', agente_id: 'agente-mock', cliente_id: 'mock-10',
      tipo: 'Email', status: 'Nao atendeu',
      comentario: 'E-mail sem resposta. Contrato Celpa vence em agosto — urgente retomar contato.',
      follow_up_data: '2026-06-05',
      created_at: '2026-05-28T10:00:00Z',
    },
    {
      id: 'at-10-1', agente_id: 'agente-mock', cliente_id: 'mock-10',
      tipo: 'Ligacao', status: 'Atendeu',
      comentario: 'Diretor Marcos confirmou interesse. Contrato Celpa vence em agosto, quer opção alternativa.',
      follow_up_data: '2026-05-28',
      created_at: '2026-05-15T15:30:00Z',
    },
  ],
  'mock-11': [
    {
      id: 'at-11-1', agente_id: 'agente-mock', cliente_id: 'mock-11',
      tipo: 'Proposta', status: 'Agendou',
      comentario: 'Proposta apresentada para 180 MWh/mês. Polo tem 5 indústrias no cluster. Reunião de decisão em julho.',
      follow_up_data: '2026-07-02',
      created_at: '2026-06-20T16:00:00Z',
    },
  ],
  'mock-12': [
    {
      id: 'at-12-2', agente_id: 'agente-mock', cliente_id: 'mock-12',
      tipo: 'Proposta', status: 'Atendeu',
      comentario: 'Fechado! 70 MWh/mês. Início em julho.',
      created_at: '2026-06-10T10:00:00Z',
    },
    {
      id: 'at-12-1', agente_id: 'agente-mock', cliente_id: 'mock-12',
      tipo: 'Reuniao', status: 'Atendeu',
      comentario: 'Reunião técnica com gerente de manutenção. Análise de carga aprovada.',
      follow_up_data: '2026-06-10',
      created_at: '2026-06-03T09:00:00Z',
    },
  ],
}
